<a href="https://colab.research.google.com/github/dwiardiyana/DATAMINING/blob/main/Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import chardet

In [3]:
dataset = pd.read_csv('DataMotor.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
print(x)
print(y)

[['Beat' nan 16000.0]
 ['Vario' 18.0 19000.0]
 ['N-max' 20.0 32000.0]
 ['Pcx' 21.0 33000.0]
 ['vixion' 16.0 27000.0]
 ['GSX 150' 18.0 nan]
 ['CBR150' nan 34000.0]
 ['Supra X' 15.0 15000.0]]
['No' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [4]:
print(x)

[['Beat' nan 16000.0]
 ['Vario' 18.0 19000.0]
 ['N-max' 20.0 32000.0]
 ['Pcx' 21.0 33000.0]
 ['vixion' 16.0 27000.0]
 ['GSX 150' 18.0 nan]
 ['CBR150' nan 34000.0]
 ['Supra X' 15.0 15000.0]]


In [5]:
print(y)

['No' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [6]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [7]:
print(x)

[['Beat' 18.0 16000.0]
 ['Vario' 18.0 19000.0]
 ['N-max' 20.0 32000.0]
 ['Pcx' 21.0 33000.0]
 ['vixion' 16.0 27000.0]
 ['GSX 150' 18.0 25142.85714285714]
 ['CBR150' 18.0 34000.0]
 ['Supra X' 15.0 15000.0]]


In [8]:
from sklearn.compose import ColumnTransformer 
from sklearn.preprocessing import OneHotEncoder
ct =  ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [9]:
print(x)

[[1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 18.0 16000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 18.0 19000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 20.0 32000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 21.0 33000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 16.0 27000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 18.0 25142.85714285714]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 18.0 34000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 15.0 15000.0]]


In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [11]:
print(y)

[0 1 1 1 0 1 0 1]


In [14]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split( x,y, test_size=0.2, random_state=1)

In [15]:
print(x_train)

[[0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 18.0 19000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 18.0 34000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 18.0 16000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 16.0 27000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 21.0 33000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 18.0 25142.85714285714]]


In [16]:
print(x_test)

[[0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 15.0 15000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 20.0 32000.0]]


In [17]:
print(y_train)

[1 0 0 0 1 1]


In [18]:
print(y_test)

[1 1]


In [19]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [20]:
print(x_train)

[[0.0 0.0 0.0 0.0 -0.4472135954999579 0.0 2.2360679774997894
  -0.44721359549995787 -0.11396057645963874 -1.010235970836946]
 [0.0 1.0 0.0 0.0 -0.4472135954999579 0.0 -0.44721359549995787
  -0.44721359549995787 -0.11396057645963874 1.2547058854878805]
 [1.0 0.0 0.0 0.0 -0.4472135954999579 0.0 -0.44721359549995787
  -0.44721359549995787 -0.11396057645963874 -1.4632243421019113]
 [0.0 0.0 0.0 0.0 -0.4472135954999579 0.0 -0.44721359549995787
  2.2360679774997894 -1.481487493975294 0.19773301920296155]
 [0.0 0.0 0.0 0.0 2.23606797749979 0.0 -0.44721359549995787
  -0.44721359549995787 1.937329799813844 1.1037097617328921]
 [0.0 0.0 1.0 0.0 -0.4472135954999579 0.0 -0.44721359549995787
  -0.44721359549995787 -0.11396057645963874 -0.08268835348487436]]


In [21]:
print(x_test)

[[0.0 0.0 0.0 0.0 -0.4472135954999579 1.0 -0.44721359549995787
  -0.44721359549995787 -2.1652509527331216 -1.6142204658568997]
 [0.0 0.0 0.0 1.0 -0.4472135954999579 0.0 -0.44721359549995787
  -0.44721359549995787 1.2535663410560165 0.9527136379779038]]
